title: Sync Savings Plugin Guide
description: An implementation guide for Sync Savings' UI Plugin
theme: just-the-docs

url: https://syncsavings.github.io/integration-guide

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
