title: Sync Savings Plugin Guide
description: An implementation guide for Sync Savings' UI Plugin
theme: just-the-docs

url: https://syncsavings.github.io/integration-guide

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
